name: Generate PDF from resume

on:
  push:
    paths:
      - "resume.md"
  workflow_dispatch:
    inputs:
      reason:
        description: "Re-generate resume PDF"
        required: false
        default: "Manual trigger"

permissions:
  contents: write

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.5.0"

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      
        # TODO: figure out paths and such 
      # - name: Run tests
      #   run: pnpm test

      - name: Generate PDF
        run: pnpm build 

      - name: Commit PDF
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor}}@users.noreply.github.com"
          git add output/art_rosnovsky_software_engineer.pdf
          git commit -am "feat: update resume PDF"
          git push
